###########
# site.title, site.url, site.author.name

title:   'Kalki7'
url:     'http://kalki7.tk'
author:
  name:  'Kalki7 Blog'


########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false

